### ISSUE TITLE
Statsgen Error

### ISSUE THREAD

**Issue by flyinghaggis** [iphelix/pack#14]
I am trying to run statsgen from a windows cmd with python installed.

when I run python statsgen.py tmp.txt
I receive the following error

File "C:\Wordlist\pack-master\statsgen.py", line 178
    print "[+] Analyzing %d%% (%d/%d) of passwords" % (self.filter_counter*100/self.total_counter, self.filter_counter, self.total_counter)

Any ideas

Rab.

**Comment by flyinghaggis** [comment]
Cancel that issue - I have solved the problem, I need to use an older 
version of python ver.27 in fact.
Thanks
Rab.

**Comment by roycewilliams** [comment]
(@flyinghaggis , you can close the issue directly yourself :) )
