### ISSUE TITLE
Order masks by cracked password per time unit

### ISSUE THREAD

**Issue by mfr-itr** [iphelix/pack#9]
By running `statgen` on my sample, I get the following rules:
```
...
?s?d?d?d?d?d?d?d,1611
?s?s,1450
?s?s?s?s?s?s?s?s?s?s?s,1267
...
```
The second one would yield much more passwords per time unit than the two others so it would be preferable to try this one first. A way to do that would be to sort using the number of passwords cracked per time unit. It can be abstract, it doesn't have to be in seconds. One ten bits password is cracked as fast as two eleven or four twelve bit passwords, so the unit could be related to `bit strength of the mask - log2(number of passwords for this mask)`. Any thoughts?

**Comment by mfr-itr** [comment]
Oops, sorry, didn't pay attention to the others scripts.
Awesome repo BTW !

**Comment by iphelix** [comment]
Oh nice! Glad you find it useful.
